// API 1 Total Scenarios

GET http://localhost:3000/todos/?status=TO%20DO

###

GET http://localhost:3000/todos/?priority=HIGH

###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

GET http://localhost:3000/todos/?search_q=play

###

//API 2 
GET http://localhost:3000/todos/2/

###

//API 3 

POST http://localhost:3000/todos
Content-Type:application/json

{
  "id": 4,
  "todo": "Learn Express JS",
  "priority": "High",
  "status": "TO DO"
}

###

//API 4 Total Scenarios

PUT http://localhost:3000/todos/1
Content-Type:application/json

{
  "todo": "Play Html"
}

###

PUT http://localhost:3000/todos/4
Content-Type:application/json

{
  "priority": "HIGH"
}

###

PUT http://localhost:3000/todos/2
Content-Type:application/json

{
  "status": "TO DO"
}

###

//API 5

DELETE http://localhost:3000/todos/3/

###